### PR TITLE
backport Pretoucher fix from 2.24

### PR DESCRIPTION
**Pull request by JerryShea**

### CODE REVIEW

**Comment by alamar** [comment]
Wasn't the whole point disabling/not recommending pretoucher in 2.23 and before that? I believe that's what we have discussed two months back.

**Comment by nicktindall** [comment]
This doesn't fix the break in CQE

**Comment by JerryShea** [comment]
In x.24 Pretoucher has been moved to QE, but it is still in 23 stable, so we should apply this fix

**Comment by alamar** [comment]
What's the status of this change?

**Comment by JerryShea** [comment]
Closing - no point in doing this

**Pull request closed without merging**
