### PR TITLE
Failing Test with successive appenders.

### PR DESCRIPTION
**Pull request by andrm**
I was expecting that the second appender would just add entries, but it rewrote them. Anything I am missing?

### CODE REVIEW

**Comment by peter-lawrey** [comment]
Each thread has only one appender as there is only one end of file. This does mean you can't track the last index appended without taking a copy.

**Comment by peter-lawrey** [comment]
Thank you for the test.
If you do an update, I have modified the test and added some comments.
Could you review them?

**Comment by andrm** [comment]
I'm not sure what you mean: A copy of the long (lastIndexAppended) or the appender?

**Comment by peter-lawrey** [comment]
Sorry, I hadn't read the test properly. You have two actual appenders in this case as you have two queues.

**Comment by andrm** [comment]
Sorry, yes, looks good.

**Comment by andrm** [comment]
I do have another problem with 4.5.21 I'm trying to reproduce, but wasn't able to do yet. I will post a test once I can. Thanks!

**Comment by peter-lawrey** [comment]
Thank you. The tests are very helpful in turning these problems around.
ᐧ

**Comment by andrm** [comment]
Thanks for the fast responses.

**Pull request merged**
