### PR TITLE
"Damaged" CQ file.

### PR DESCRIPTION
**Pull request by andrm**
Test for a damaged CQ file. It would be great if CQ could extract more
entries from such a "damaged" file and fail more gracefully.

### CODE REVIEW

**Comment by andrm** [comment]
Hi, I tried to contact you via the sales email address, but got no response. We are interested in support/consulting. Could you please contact me? Thanks.

**Comment by peter-lawrey** [comment]
Hi. You have mentioned this before but I definitely haven't seen such an
email. Please email me
Peter.lawrey
At
chronicle.software

**Comment by andrm** [comment]
Ok, email is away..

**Comment by peter-lawrey** [comment]
Hmm. Not received it yet. What is your email?

**Comment by andrm** [comment]
andreas.mack at konsec dot com

**Comment by andrm** [comment]
I got your email, did you get my reply?

**Pull request merged**
