### PR TITLE
Backwards roll failing tests

### PR DESCRIPTION
**Pull request by scottkidder**
Both tests failing

### CODE REVIEW

**Comment by scottkidder** [comment]
Second commit is a working fix for when the store becomes null, rather than going to firstIndex(), attemptToAdvanceCycle(). All tests are passing but handling a BACKWARD tailer should be cleaner.

**Comment by peter-lawrey** [comment]
This test has been added. Can you re-issue this PR if there is anything missing?

**Comment by peter-lawrey** [comment]
I don't think this has been pulling manually after all.

**Comment by peter-lawrey** [comment]
Would you be able to update and re-issue this PR?

**Pull request closed without merging**
