### PR TITLE
Document AppenderListener, Fix #1035

### LINKED ISSUE #1035: Document AppenderListener

### PR DESCRIPTION
**Pull request by minborg**

### CODE REVIEW

**Review by JerryShea — APPROVED** [review]
love it

**Comment by minborg** [comment]
> love it

Thanks @JerryShea  :-)

**Review by peter-lawrey — COMMENTED** [review]
+1

**Comment by peter-lawrey** [comment]
In particular, we may support asynchronous calls (from the writes) in a manner that might need to be restarted.

**Pull request merged**
